/**
 * POST /api/workflows/generate
 *
 * Takes a natural-language prompt from the user and returns
 * a workflow graph (nodes + edges) generated by an AI model.
 *
 * This is used by the visual workflow builder so users can
 * describe an automation in plain text and get a starting graph.
 *
 * Authentication required — uses accountId from session so the
 * generated workflow can later be saved to the correct account.
 */

import { NextResponse } from "next/server";
import { requireAccountId } from "@/lib/auth/session";
import { executeLLMCompletion } from "@/lib/workflow/ai-client";

export const dynamic = "force-dynamic";

// ── System Prompt ─────────────────────────────────────────────────────────────

const WORKFLOW_BUILDER_SYSTEM_PROMPT = `
You are AnaOS AI, an expert automation workflow compiler.
The user will describe an automation in plain language.
Output a strictly valid JSON object — no markdown, no explanations, just JSON.

Schema:
{
  "nodes": [
    {
      "id": "string",
      "type": "trigger_whatsapp" | "trigger_lead_created" | "trigger_stage_changed" | "trigger_property_listed" | "send_whatsapp" | "send_email" | "ai_respond" | "ai_classify" | "condition" | "wait" | "crm_update_lead_stage" | "crm_assign_agent",
      "name": "string",
      "position": { "x": number, "y": number },
      "config": {},
      "inputs": ["node_id"],
      "outputs": ["node_id"]
    }
  ],
  "edges": [
    { "id": "string", "source": "node_id", "target": "node_id" }
  ]
}

Rules:
- Every workflow must have exactly one trigger node
- Node IDs must be unique strings (use "node-1", "node-2", etc.)
- Position nodes left-to-right with x incrementing by 200 each step
- The "outputs" array in each node must list the IDs of the next nodes
- Keep it simple — match the user's request closely, no extra steps
`.trim();

// ── Route Handler ─────────────────────────────────────────────────────────────

export async function POST(request: Request): Promise<NextResponse> {
  try {
    // Auth required — not a public endpoint
    const accountId = await requireAccountId();

    const body = await request.json();
    const { prompt } = body;

    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return NextResponse.json({ error: "prompt is required" }, { status: 400 });
    }

    // Call LLM to generate workflow JSON
    const rawJson = await executeLLMCompletion({
      provider: "claude",
      model: "claude-3-5-sonnet-20240620",
      systemPrompt: WORKFLOW_BUILDER_SYSTEM_PROMPT,
      userMessage: prompt.trim(),
      maxTokens: 2000,
      temperature: 0.1, // Low temperature for deterministic structure
      credentialId: "",
      accountId,
    });

    // Strip markdown fences if model added them
    const cleaned = rawJson
      .trim()
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/```\s*$/, "");

    let workflow: unknown;
    try {
      workflow = JSON.parse(cleaned);
    } catch {
      console.error("[Workflow Generate] Failed to parse AI response:", cleaned.slice(0, 200));
      return NextResponse.json(
        { error: "AI returned invalid JSON — please rephrase your prompt" },
        { status: 422 }
      );
    }

    return NextResponse.json({ workflow });
  } catch (err) {
    if (err instanceof Error && err.message === "Unauthorized") return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[Workflow Generate]", message);
    return NextResponse.json(
      { error: "Failed to generate workflow", details: message },
      { status: 500 }
    );
  }
}
